### ISSUE TITLE
Positionen der Sensoren noch nicht bekannt

### ISSUE THREAD

**Issue by ampxtreme** [ampxtreme/Gruppe-2---Mars-Rover-Challenge#1]

**Comment by fabioaufinger** [comment]
Würde vorschlagen 3x Ultraschall vorne am Gehäuse (mitte und schräg links/rechts), vielleicht 1x Ultraschall hinten mittig.
Die Linetracker müssen wir an irgendeiner Achse nach innen bei den Reifen anbringen oder ähnlich (müssen nahe am Boden sein)
Kamera kommt vorne ans Gehäuse

**Comment by JoeUniv** [comment]
Bei den Linetrackern müssen wir aber beachten das wir nicht wissen wo die Linien verlaufen, wenn die alle eher mittig vom track sind und unsere sensoren außen auf den Achsen dann steht unser Fahrzeug zur hälfte nach draußen.

**Comment by ampxtreme** [comment]
> Bei den Linetrackern müssen wir aber beachten das wir nicht wissen wo die Linien verlaufen, wenn die alle eher mittig vom track sind und unsere sensoren außen auf den Achsen dann steht unser Fahrzeug zur hälfte nach draußen.

Du meinst wenn wir die LT eher an den Rädern anbringen stehen wir rechts oder links zu weit raus und werden dann bespritzt?

**Comment by mausausdruck1** [comment]
Vielleicht müssen wir die Achsen nach innen etwas verlängern für die Tracker. Ansonsten seh ich die Sensoren wie @fabioaufinger.

**Comment by hs123xyz** [comment]
mir fällt auf, dass wir auch die line tracker evtl. nochmal zusätzlich vor Wasser schützen müssten mit einer Abdeckung oder ähnlichem

**Comment by Eli93TRO** [comment]
Schrumpfschlauch?

**Comment by JoeUniv** [comment]
plus Heißklebe pistole

**Comment by JoeUniv** [comment]
Linetracker mechanisch zentral herunter lassen

**Comment by JoeUniv** [comment]
Linetracking über die Kamera

**Comment by JoeUniv** [comment]
BRÜCKENKURS:
Linetracker an  Fahrwerk anbringen um zu wissen ob ein Reifen in der Luft hängt oder Bodenkontakt hat.
