### ISSUE TITLE
Poster von Tag 1

### ISSUE THREAD

**Issue by mausausdruck1** [ampxtreme/Gruppe-2---Mars-Rover-Challenge#10]
Hat jemand die Poster fotographiert und kann die ins Projektwiki oder sonstwohin tun? Wäre cool. Oder gibt es die noch irgendwo?

**Comment by ampxtreme** [comment]
Das hier? https://photos.app.goo.gl/zjZwxRgjmU4h8CiR8

**Comment by mausausdruck1** [comment]
Top, schon einmal eines. Gibts die anderen auch noch?

**Comment by ampxtreme** [comment]
Ich habe sonst nur das hier: https://photos.app.goo.gl/zbxsqBhPGwhCcMCr8
