### ISSUE TITLE
Elektronik

### ISSUE THREAD

**Issue by JoeUniv** [ampxtreme/Gruppe-2---Mars-Rover-Challenge#11]
Da wir am Samstag die Elektronik testen müssen sollten wir am Freitag alle Sensoren etz. aus der Uni mitnehmen.

Wir brauchen:
- 6x Drehzalmesser (LM393)
- 4x Ultraschall (HC-SR04)
- 4x Linetracker(KY - 033)
- 1x Cam 
- Gyro( MPU6000 oder MPU6050)(im Notfall MPU9250)
- 4x H-Brücke (DRV8847)
- Raspberry Pi 3
- I2C
- Rotary Switch 

Sollte euch noch was einfallen, bitte anfügen!!!

**Comment by JoeUniv** [comment]
- Pins
- Kabel
- Steckplatine

**Comment by mausausdruck1** [comment]
Ich bin mir nicht sicher, ob die H Brücken da herum liegen, die hat der Udo (?) uns ja empfohlen. Die wären aber wichtig!
