### ISSUE TITLE
Teamname gesucht

### ISSUE THREAD

**Issue by mausausdruck1** [ampxtreme/Gruppe-2---Mars-Rover-Challenge#2]

**Comment by spsmichi** [comment]
Home of Tomorrow (HOT)

**Comment by ampxtreme** [comment]
Ich hab die Idee vom Fabio schon wieder vergessen.
Iwas mit KASA oder?
Kufstein Aeronautics and Space Administration

**Comment by fabioaufinger** [comment]
KSA - Kufstein Space Agency
KMA - Kufstein Mars Agency
waren meine Vorschläge

**Comment by ampxtreme** [comment]
Bin für HOT und KSA - beides gut. Wobei mir HOT ein kleines bisschen besser gefällt.

**Comment by spsmichi** [comment]
Ich find HOT ziemlich hot...

**Comment by hs123xyz** [comment]
finde auch hot gut. Kann ein Logo erstellen, wenn Ihr wollt. Steht nämlich auch auf der TO DO Liste...

**Comment by ampxtreme** [comment]
@mausausdruck1 @fabioaufinger @Eli93TRO @Joe: Passt das für Euch auch? Dann können wir den Punkt schließen.
