### ISSUE TITLE
Gehäusegröße für Platine & Raspberry-Pi sowie ggf. Akku noch nicht bekannt.

### ISSUE THREAD

**Issue by ampxtreme** [ampxtreme/Gruppe-2---Mars-Rover-Challenge#3]
Johannes und ich benötigen die verfügbare Gehäusegröße für die Platine + Raspberry Pi, wobei unser Platzbedarf ungefähr der Größe von ~Raspberry Pi entsprechen (2x Raspb. + 1x Platine).

**Comment by ampxtreme** [comment]
ungeführ brauchen wir 12cm breite und 17cm länge platz.
Batterien verstauen wir unter der Platine und den beiden Raspberries.
Ich lade euch noch eine skizze hoch.

**Comment by JoeUniv** [comment]
![img_9059](https://user-images.githubusercontent.com/46840123/51546486-8648ed80-1e64-11e9-83fd-d082f24fd8a6.JPG)

**Comment by JoeUniv** [comment]
Die Länge eher mit 20cm rechnen.
Günther meinte das die Batterie und was sonst noch so anfällt darunter genügend platz hat.

**Comment by Eli93TRO** [comment]
Habe das gezeichnete gerade raufgeladen.
der Platz für die gesamte Elektronik ist 180*150*h35mm
