### ISSUE TITLE
Schutz gegen Spritzwasser der el. Komponenten sicherstellen

### ISSUE THREAD

**Issue by ampxtreme** [ampxtreme/Gruppe-2---Mars-Rover-Challenge#4]

**Comment by spsmichi** [comment]
Heißkleber auf die betroffenen Stellen. War auch die Idee vom Günter.

**Comment by ampxtreme** [comment]
Jo, das ist sehr gut. Das Gehäuse könnte ggf. von unten ein zwei kleine Löcher/Schlitze erhalten damit ein wenig Luft zirkulieren kann. Zumindest 100% Luftdicht sollten wir es nicht bauen.

Als Vorschlag zur Öffnung des Gehäuses: Öffnung seitlich mit einer Klappe welche sich einfach durch Steckverbindungen abnehmen lässt. Drüber stülpen wir dann für die Fahr ein leicht größeres Gehäuse (nur ein kleines Stück) für zusätzlichen Schutz.

**Comment by spsmichi** [comment]
die steckverbindung ist wieder ein kritisches teil. wird es wirklich zu heiß?

**Comment by Eli93TRO** [comment]
Laut Günther ist die Hitze überhaupt kein Problem

**Comment by ampxtreme** [comment]
> Laut Günther ist die Hitze überhaupt kein Problem

... wenn nicht komplett Luftdicht verschlossen wird ;-)

Wir müssen halt rigendwie ein bisschen die Wartbarkeit sicherstellen. Ich könnte mir vorstellen, dass für kurze Zeit Spritzwasser auch bei einer Steckverbindung nicht viel passiert wenn sie gut passt. Was meint ihr?

**Comment by JoeUniv** [comment]
nachdem die anderen so fest draufspritzen können wie sie wollen würde ich die zu Luft eher von unten Regulieren.
Wie wärs wir denken über eine Konstruktion nach die man auf den Kopf legen muss um sie zu öffnen? -> DIe "Tür" ist auf dem Bauch des Fahrzeugs.
