### ISSUE TITLE
Klebeband für den Reifen

### ISSUE THREAD

**Issue by spsmichi** [ampxtreme/Gruppe-2---Mars-Rover-Challenge#5]
Habe verschiedene Möglichkeiten raus gesucht.

[Uploading Klebeband.docx…]()

**Comment by spsmichi** [comment]
[Klebeband.pdf](https://github.com/ampxtreme/Gruppe-2---Mars-Rover-Challenge/files/2780155/Klebeband.pdf)

**Comment by mausausdruck1** [comment]
Ich wäre für das Gummi-Band.
Anti-Rutsch ist für die Kombination Gummisole/Band sicher gut, aber unser System wäre dann Holzplatte/Antirutschband.

**Comment by fabioaufinger** [comment]
Und wenn wir einfach Gummibänder um die Lauffläche spannen?

**Comment by JoeUniv** [comment]
meinst du damit Gummiringerl? 
Das könnte funktionieren

**Comment by ampxtreme** [comment]
Die dürften dann halt nicht stark gespannt sein, außerdem müssen wir bedenken, dass es uns die beim "Drehen" runterziehen kann.

Ich wäre auch für das Gummi-Klebeband, hätte allerdings noch einen Vorschlag, da ich das im Auto habe und weiß das es gut funktioniert:

https://www.amazon.de/Filmer-37119-Antirutschmatte-120-zuschneidbar/dp/B004U5WXRY/ref=sr_1_3?ie=UTF8&qid=1548172953&sr=8-3&keywords=anti+rutsch+matte

**Comment by JoeUniv** [comment]
müsste man probieren, könnte mir vorstellen das die gummiringerl auch gespannt eine gute reibung haben.
Auf jeden Fall um einiges besser als die Reifen die wir getestet haben.
Das Klebeband ist aber auch nicht viel komplexer umzusetzen.

**Comment by spsmichi** [comment]
@ampxtreme das ist nich selbstklebend oder? 

Ich bestelle das gummiklebeband und zusätzlich normale gummis.
