### ISSUE TITLE
Test-Verkabelung

### ISSUE THREAD

**Issue by mausausdruck1** [ampxtreme/Gruppe-2---Mars-Rover-Challenge#9]
Hallo Zusammen,

können wir für Samstag eine Test Verkabelung mal einpeilen? Das würde sehr bei der SW-Entwicklung helfen.
1) Sensoren
2) Motoren idealerweise über diese neue  I2C H-Brücke. Kann man die bis Samstag organisieren? Wer macht das? 

Andere Vorschläge?

**Comment by JoeUniv** [comment]
Habe zu den einzelnen teilen die wir benötigen ein eigenes Issue erstellt -> Siehe Elektronik
